### ISSUE TITLE
[Bug]: The plugin6.(*GRPCProvider).ReadDataSource request was cancelled

### ISSUE THREAD

**Issue by premadhas** [TiVo/terraform-provider-splunk-itsi#235] opened 2023-07-06 16:02 UTC
## Description
Plugin is crashed while performing 'terraform plan'

## Steps to Reproduce
terraform plan

## Expected Behavior
Should receive execution plan

## Current Behavior
Plugin crashed

### ITSI Terraform Provider version

1.0.0-beta.5

## Environment
Terraform version and OS: Mac - Ventura 13.3.1
ITSI version: 4.16.0
Splunk version: Cloud Version:9.0.2303.201

### Relevant log output

```shell
Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ReadDataSource request was cancelled.
╵

Stack trace from the terraform-provider-splunk-itsi_v1.0.0-beta.5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x17ffc99]

goroutine 60 [running]:
github.com/tivo/terraform-provider-splunk-itsi/provider.(*dataSourceEntityType).Read(0xc000148150, {0x1b4f100, 0xc0003180c0}, {{{{0x1b53bc8, 0xc000319530}, {0x18fcbe0, 0xc000319290}}, {0x1b54e00, 0xc0002d8580}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/tivo/terraform-provider-splunk-itsi/provider/datasource_entity_type.go:83 +0x1d9
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0000f7600, {0x1b4f100, 0xc0003180c0}, 0xc0003181b0, 0xc0001bb440)
        github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/server_readdatasource.go:79 +0x4ae
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0000f7600, {0x1b4f100?, 0xc0000b3aa0?}, 0xc00030b460)
        github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/proto6server/server_readdatasource.go:55 +0x42f
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadDataSource({0xc0002f0a50, 0xc0002f0ab0, {0xc00030aaa0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadDataSource.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0003d6000, {0x1b4f100?, 0xc00080a6c0?}, 0xc00007e5a0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:656 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x19c7bc0?, 0xc0003d6000}, {0x1b4f100, 0xc00080a6c0}, 0xc0003475e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:455 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001721e0, {0x1b53eb8, 0xc000582340}, 0xc0005c90e0, 0xc0003cf350, 0x20aee90, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001721e0, {0x1b53eb8, 0xc000582340}, 0xc0005c90e0, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

Error: The terraform-provider-splunk-itsi_v1.0.0-beta.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by dmitrykruglov** [comment] 2023-07-06 17:49
Hi @premadhas,
this is a duplicate of #231 and should be fixed in [v1.0.0-beta.6](https://github.com/TiVo/terraform-provider-splunk-itsi/releases/tag/v1.0.0-beta.6)

**Closed** 2023-07-07 06:20 UTC
Labels: bug
